spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FootballClub;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=139
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver